### ISSUE TITLE
Can you upload the data to Google Drive instead of Baidu?

### ISSUE THREAD

**Issue by limhasic** [YhuoyuH/RetinexMamba#4]
Baidu membership registration is blocked in my country.

**Comment by YhuoyuH** [comment]
I apologize for not considering this problem.We will upload to Google Drive in one week.Please pay attention to our repository.
---- Replied Message ----
***@***.***>Date6/5/2024 ***@***.***>***@***.***>Subject[YhuoyuH/RetinexMamba] Can you upload the data to Google Drive instead of Baidu? (Issue #4)
Baidu membership registration is blocked in my country.

**Comment by limhasic** [comment]
Thank you for your reply even though you are busy. 

Now that this issue has been resolved, I'll close it.
